# Álgebra Lineal con Python

En este cuaderno exploraremos los conceptos fundamentales del álgebra lineal usando Python y la librería **NumPy**. NumPy es una herramienta esencial para realizar cálculos numéricos en Python, especialmente para trabajar con vectores y matrices.

Para comenzar, importamos NumPy con el alias `np`, que es la convención estándar.

In [1]:
import numpy as np

---
## 1. Vectores y Matrices

### Vectores

Un **vector** es un arreglo unidimensional de números. Se puede pensar como una lista ordenada de valores. Los vectores pueden ser columnas o filas:

$$
\mathbf{u} = \begin{bmatrix} 3 \\ -1 \\ 5 \end{bmatrix} \qquad
\mathbf{v} = \begin{bmatrix} 2 & 7 & -4 \end{bmatrix}
$$

En NumPy, los vectores se representan como arreglos (`array`).

In [2]:
# Vector columna (forma matricial con 1 columna)
u = np.array([[3], [-1], [5]])
print("Vector columna u:")
print(u)
print("Dimensiones (shape):", u.shape)  # (3, 1) = 3 filas, 1 columna

Vector columna u:
[[ 3]
 [-1]
 [ 5]]
Dimensiones (shape): (3, 1)


In [3]:
# Vector fila
v = np.array([[2, 7, -4]])
print("Vector fila v:")
print(v)
print("Dimensiones (shape):", v.shape)  # (1, 3) = 1 fila, 3 columnas

Vector fila v:
[[ 2  7 -4]]
Dimensiones (shape): (1, 3)


### Matrices

Una **matriz** es un arreglo bidimensional de números organizado en filas y columnas. Se dice que una matriz tiene dimensiones $m \times n$ cuando tiene $m$ filas y $n$ columnas.

$$
A = \begin{bmatrix} 1 & 3 \\ 2 & -1 \end{bmatrix}_{2\times 2}
\qquad
B = \begin{bmatrix} 4 & 0 & -2 \\ 1 & 5 & 3 \end{bmatrix}_{2\times 3}
\qquad
C = \begin{bmatrix} 2 & -1 \\ 0 & 4 \\ 3 & 1 \end{bmatrix}_{3\times 2}
$$

Usamos la notación $a_{ij}$ para referirnos al elemento en la fila $i$ y columna $j$ de la matriz $A$. **Importante:** en Python el índice comienza en 0.

In [4]:
# Definir matrices con np.array
A = np.array([[1, 3],
              [2, -1]])

B = np.array([[4,  0, -2],
              [1,  5,  3]])

C = np.array([[ 2, -1],
              [ 0,  4],
              [ 3,  1]])

print("Matriz A (2x2):")
print(A)
print()
print("Matriz B (2x3):")
print(B)
print()
print("Matriz C (3x2):")
print(C)

Matriz A (2x2):
[[ 1  3]
 [ 2 -1]]

Matriz B (2x3):
[[ 4  0 -2]
 [ 1  5  3]]

Matriz C (3x2):
[[ 2 -1]
 [ 0  4]
 [ 3  1]]


In [5]:
# Consultar dimensiones
print("Dimensiones de A:", A.shape, "→", A.shape[0], "filas,", A.shape[1], "columnas")
print("Dimensiones de B:", B.shape, "→", B.shape[0], "filas,", B.shape[1], "columnas")
print("Dimensiones de C:", C.shape, "→", C.shape[0], "filas,", C.shape[1], "columnas")

Dimensiones de A: (2, 2) → 2 filas, 2 columnas
Dimensiones de B: (2, 3) → 2 filas, 3 columnas
Dimensiones de C: (3, 2) → 3 filas, 2 columnas


In [6]:
# Acceder a elementos individuales
# Recordar: los índices en Python empiezan en 0
print("Elemento A[0,0] (fila 1, col 1):", A[0, 0])  # = 1
print("Elemento A[0,1] (fila 1, col 2):", A[0, 1])  # = 3
print("Elemento A[1,0] (fila 2, col 1):", A[1, 0])  # = 2
print("Elemento B[1,2] (fila 2, col 3):", B[1, 2])  # = 3

Elemento A[0,0] (fila 1, col 1): 1
Elemento A[0,1] (fila 1, col 2): 3
Elemento A[1,0] (fila 2, col 1): 2
Elemento B[1,2] (fila 2, col 3): 3


### Matrices especiales

Algunas matrices tienen propiedades especiales que son muy útiles en álgebra lineal:

- **Matriz de ceros**: todos sus elementos son 0.
- **Matriz identidad** $I$: elementos 1 en la diagonal principal y 0 en el resto. Cumple que $AI = IA = A$.
- **Matriz diagonal**: solo tiene elementos no nulos en la diagonal principal.

In [7]:
# Matriz de ceros 3x3
Z = np.zeros((3, 3))
print("Matriz de ceros 3x3:")
print(Z)
print()

Matriz de ceros 3x3:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



In [8]:
# Matriz identidad 4x4
I4 = np.eye(4)
print("Matriz identidad 4x4:")
print(I4)

Matriz identidad 4x4:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
# Verificar propiedad de la identidad: A * I = A
I2 = np.eye(2)
print("A @ I2 =")
print(A @ I2)
print("Es igual a A:", np.array_equal(A, A @ I2))

A @ I2 =
[[ 1.  3.]
 [ 2. -1.]]
Es igual a A: True


### Transpuesta de una matriz

La **transpuesta** de una matriz $A$ se denota $A^T$ y se obtiene intercambiando filas por columnas: el elemento $a_{ij}$ pasa a la posición $a_{ji}$.

$$
A = \begin{bmatrix} 1 & 3 \\ 2 & -1 \end{bmatrix} \qquad \Rightarrow \qquad
A^T = \begin{bmatrix} 1 & 2 \\ 3 & -1 \end{bmatrix}
$$

In [10]:
print("Matriz B (2x3):")
print(B)
print()
print("Transpuesta de B (3x2):")
print(B.transpose())

Matriz B (2x3):
[[ 4  0 -2]
 [ 1  5  3]]

Transpuesta de B (3x2):
[[ 4  1]
 [ 0  5]
 [-2  3]]


---
## 2. Suma de Matrices

Dos matrices se pueden sumar **solo si tienen las mismas dimensiones**. La suma se realiza elemento a elemento:

$$
(A + B)_{ij} = a_{ij} + b_{ij}
$$

**Ejemplo:**
$$
A = \begin{bmatrix} 1 & 3 \\ 2 & -1 \end{bmatrix}, \quad
C = \begin{bmatrix} -2 & 4 \\ 0 & 5 \end{bmatrix} \qquad \Rightarrow \qquad
A + C = \begin{bmatrix} 1+(-2) & 3+4 \\ 2+0 & -1+5 \end{bmatrix} = \begin{bmatrix} -1 & 7 \\ 2 & 4 \end{bmatrix}
$$

In [11]:
A = np.array([[1,  3],
              [2, -1]])

C = np.array([[-2, 4],
              [ 0, 5]])

suma = A + C
print("A =")
print(A)
print()
print("C =")
print(C)
print()
print("A + C =")
print(suma)

A =
[[ 1  3]
 [ 2 -1]]

C =
[[-2  4]
 [ 0  5]]

A + C =
[[-1  7]
 [ 2  4]]


También se puede calcular la diferencia $A - C$ de la misma manera:

In [12]:
diferencia = A - C
print("A - C =")
print(diferencia)

A - C =
[[ 3 -1]
 [ 2 -6]]


Si intentamos sumar matrices de dimensiones distintas, NumPy lanzará un error:

In [13]:
B = np.array([[4,  0, -2],
              [1,  5,  3]])

# Intento de suma de matrices con dimensiones distintas
try:
    resultado = A + B  # A es 2x2, B es 2x3 → Error!
except ValueError as e:
    print("Error al sumar A (2x2) con B (2x3):")
    print(e)

Error al sumar A (2x2) con B (2x3):
operands could not be broadcast together with shapes (2,2) (2,3) 


---
## 3. Multiplicación por Escalar

Un **escalar** es simplemente un número. Cuando multiplicamos una matriz por un escalar $k$, multiplicamos **cada elemento** de la matriz por ese número:

$$
(kA)_{ij} = k \cdot a_{ij}
$$

**Ejemplo:**
$$
3 \cdot \begin{bmatrix} 1 & 3 \\ 2 & -1 \end{bmatrix} = \begin{bmatrix} 3 & 9 \\ 6 & -3 \end{bmatrix}
$$

In [14]:
A = np.array([[1,  3],
              [2, -1]])

print("A =")
print(A)
print()

print("3 * A =")
print(3 * A)
print()

print("-1 * A =")
print(-1 * A)
print()

print("0.5 * A =")
print(0.5 * A)

A =
[[ 1  3]
 [ 2 -1]]

3 * A =
[[ 3  9]
 [ 6 -3]]

-1 * A =
[[-1 -3]
 [-2  1]]

0.5 * A =
[[ 0.5  1.5]
 [ 1.  -0.5]]


In [15]:
# Ejemplo combinado: combinación lineal de matrices
C = np.array([[-2, 4],
              [ 0, 5]])

resultado = 2*A - 3*C
print("2A - 3C =")
print(resultado)

2A - 3C =
[[  8  -6]
 [  4 -17]]


---
## 4. Multiplicación entre Matrices

La multiplicación de matrices es la operación más importante —y menos intuitiva— del álgebra lineal.

Para poder multiplicar $A \cdot B$, el **número de columnas de $A$** debe ser igual al **número de filas de $B$**.

Si $A$ es $m \times n$ y $B$ es $n \times k$, entonces el producto $AB$ es una matriz $m \times k$.

El elemento en la posición $(i, j)$ del producto se calcula como:
$$
(AB)_{ij} = \sum_{r=1}^{n} a_{ir} \cdot b_{rj}
$$

Es decir, es el **producto punto** de la fila $i$ de $A$ con la columna $j$ de $B$.

**Ejemplo:**
$$
A = \begin{bmatrix} 1 & 3 \\ 2 & -1 \end{bmatrix}_{2\times 2}, \quad
B = \begin{bmatrix} 4 & 0 & -2 \\ 1 & 5 & 3 \end{bmatrix}_{2\times 3}
\qquad \Rightarrow \qquad AB \text{ es } 2\times 3
$$

Calculemos el elemento $(AB)_{11}$:
$$
(AB)_{11} = 1 \cdot 4 + 3 \cdot 1 = 7
$$

Y el elemento $(AB)_{12}$:
$$
(AB)_{12} = 1 \cdot 0 + 3 \cdot 5 = 15
$$

In [16]:
A = np.array([[1,  3],
              [2, -1]])

B = np.array([[4,  0, -2],
              [1,  5,  3]])

# Multiplicación de matrices con el operador @
AB = A @ B

print("A (2x2):")
print(A)
print()
print("B (2x3):")
print(B)
print()
print("A @ B (2x3):")
print(AB)

A (2x2):
[[ 1  3]
 [ 2 -1]]

B (2x3):
[[ 4  0 -2]
 [ 1  5  3]]

A @ B (2x3):
[[ 7 15  7]
 [ 7 -5 -7]]


In [17]:
# Multiplicación de vector por matriz (transformación lineal)
x = np.array([[2], [-1]])  # vector columna 2x1

Ax = A @ x
print("Vector x:")
print(x)
print()
print("A @ x =")
print(Ax)

Vector x:
[[ 2]
 [-1]]

A @ x =
[[-1]
 [ 5]]


### ⚠️ Diferencia entre `*` y `@`

En NumPy, el operador `*` realiza multiplicación **elemento a elemento** (no es multiplicación de matrices), mientras que `@` realiza la **multiplicación matricial** correcta.

In [18]:
P = np.array([[1, 2],
              [3, 4]])

Q = np.array([[5, 6],
              [7, 8]])

print("P * Q  (elemento a elemento — NO es producto matricial):")
print(P * Q)
print()
print("P @ Q  (producto matricial correcto):")
print(P @ Q)

P * Q  (elemento a elemento — NO es producto matricial):
[[ 5 12]
 [21 32]]

P @ Q  (producto matricial correcto):
[[19 22]
 [43 50]]


---
## 5. Propiedades de la Suma y de la Multiplicación

Las operaciones con matrices cumplen varias propiedades algebraicas importantes. Sean $A$, $B$ y $C$ matrices de dimensiones compatibles, y $k$, $s$ escalares.

### Propiedades de la Suma

| Propiedad | Expresión |
|---|---|
| Conmutativa | $A + B = B + A$ |
| Asociativa | $(A + B) + C = A + (B + C)$ |
| Elemento neutro | $A + 0 = A$ |
| Elemento inverso | $A + (-A) = 0$ |

### Propiedades de la Multiplicación

| Propiedad | Expresión |
|---|---|
| Asociativa | $(AB)C = A(BC)$ |
| Distributiva (izquierda) | $A(B + C) = AB + AC$ |
| Distributiva (derecha) | $(A + B)C = AC + BC$ |
| Escalar distributivo | $k(A + B) = kA + kB$ |
| Identidad | $AI = IA = A$ |

### ⚠️ La multiplicación de matrices NO es conmutativa

En general, $AB \neq BA$. Esta es una diferencia fundamental con los números reales.

In [19]:
# Verificar que la suma es conmutativa
A = np.array([[1, 3], [2, -1]])
C = np.array([[-2, 4], [0, 5]])

print("A + C =")
print(A + C)
print()
print("C + A =")
print(C + A)
print()
print("¿A + C == C + A?", np.array_equal(A + C, C + A))

A + C =
[[-1  7]
 [ 2  4]]

C + A =
[[-1  7]
 [ 2  4]]

¿A + C == C + A? True


In [20]:
# Verificar propiedad distributiva: A(B + C) = AB + AC
A = np.array([[2, 1], [-1, 3]])
B = np.array([[1, 0], [2, 4]])
C = np.array([[3, -1], [0, 2]])

lado_izquierdo = A @ (B + C)
lado_derecho   = A @ B + A @ C

print("A(B + C) =")
print(lado_izquierdo)
print()
print("AB + AC =")
print(lado_derecho)
print()
print("¿Son iguales?", np.array_equal(lado_izquierdo, lado_derecho))

A(B + C) =
[[10  4]
 [ 2 19]]

AB + AC =
[[10  4]
 [ 2 19]]

¿Son iguales? True


In [21]:
# Demostrar que AB ≠ BA en general
A = np.random.randint(-5, 6, size=(3, 3))
B = np.random.randint(-5, 6, size=(3, 3))

print("A @ B =")
print(A @ B)
print()
print("B @ A =")
print(B @ A)
print()
print("¿AB == BA?", np.array_equal(A @ B, B @ A))
print("→ En general, el producto matricial NO es conmutativo.")

A @ B =
[[-19 -23  -3]
 [-25 -20   0]
 [  0 -20  15]]

B @ A =
[[-20  29 -11]
 [ 20  15  20]
 [-25 -14 -19]]

¿AB == BA? False
→ En general, el producto matricial NO es conmutativo.


In [22]:
# Verificar propiedad asociativa: (AB)C = A(BC)
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 1], [2, -1]])
C = np.array([[3, 0], [1, 2]])

izq = (A @ B) @ C
der =  A @ (B @ C)

print("(AB)C =")
print(izq)
print()
print("A(BC) =")
print(der)
print()
print("¿Son iguales?", np.array_equal(izq, der))

(AB)C =
[[11 -2]
 [23 -2]]

A(BC) =
[[11 -2]
 [23 -2]]

¿Son iguales? True


### Propiedad de la transpuesta

Dos propiedades útiles de la transpuesta relacionadas con la multiplicación:

$$
(AB)^T = B^T A^T \qquad \text{(el orden se invierte)}
$$

$$
(A + B)^T = A^T + B^T
$$

In [23]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[0, 1], [2, -1]])

izq = (A @ B).transpose()
der = B.transpose() @ A.transpose()

print("(AB)^T =")
print(izq)
print()
print("B^T * A^T =")
print(der)
print()
print("¿Son iguales?", np.array_equal(izq, der))

(AB)^T =
[[ 4  8]
 [-1 -1]]

B^T * A^T =
[[ 4  8]
 [-1 -1]]

¿Son iguales? True


---
## 6. Transformaciones Matriciales

Una **transformación matricial** es una función $T: \mathbb{R}^n \to \mathbb{R}^m$ definida mediante la multiplicación por una matriz:

$$
T(\mathbf{x}) = A\mathbf{x}
$$

donde $A$ es una matriz $m \times n$ y $\mathbf{x}$ es un vector en $\mathbb{R}^n$.

Toda transformación matricial es **lineal**, es decir, cumple:
- $T(\mathbf{u} + \mathbf{v}) = T(\mathbf{u}) + T(\mathbf{v})$
- $T(k\mathbf{u}) = k \cdot T(\mathbf{u})$

### Representación matricial estándar

Para encontrar la matriz $[T]$ que representa una transformación, calculamos la imagen de cada vector de la base estándar $\{e_1, e_2, \ldots, e_n\}$ y los colocamos como **columnas** de $[T]$:

$$
[T] = \begin{bmatrix} | & | & & | \\ T(e_1) & T(e_2) & \cdots & T(e_n) \\ | & | & & | \end{bmatrix}
$$

### Ejemplo 1: Transformación de $\mathbb{R}^2$ a $\mathbb{R}^3$

Sea la transformación $T: \mathbb{R}^2 \to \mathbb{R}^3$ definida por:

$$
T\!\left(\begin{bmatrix} x_1 \\ x_2 \end{bmatrix}\right) =
\begin{bmatrix} 2x_1 - x_2 \\ x_1 + 3x_2 \\ 4x_2 \end{bmatrix}
$$

La matriz estándar se obtiene aplicando $T$ a los vectores de la base:

$$
T(e_1) = T\!\left(\begin{bmatrix}1\\0\end{bmatrix}\right) = \begin{bmatrix}2\\1\\0\end{bmatrix}, \quad
T(e_2) = T\!\left(\begin{bmatrix}0\\1\end{bmatrix}\right) = \begin{bmatrix}-1\\3\\4\end{bmatrix}
$$

Por lo tanto:
$$
[T] = \begin{bmatrix} 2 & -1 \\ 1 & 3 \\ 0 & 4 \end{bmatrix}
$$

In [24]:
# Matriz estándar de la transformación T
T_mat = np.array([[ 2, -1],
                  [ 1,  3],
                  [ 0,  4]])

# Aplicar T a un vector específico
x = np.array([[3], [2]])

print("Matriz de la transformación [T] (3x2):")
print(T_mat)
print()
print("Vector de entrada x:")
print(x)
print()
print("T(x) = [T] * x :")
print(T_mat @ x)

Matriz de la transformación [T] (3x2):
[[ 2 -1]
 [ 1  3]
 [ 0  4]]

Vector de entrada x:
[[3]
 [2]]

T(x) = [T] * x :
[[4]
 [9]
 [8]]


### Ejemplo 2: Rotación en $\mathbb{R}^2$

Una de las transformaciones más importantes es la **rotación**. La transformación que rota un vector en $\mathbb{R}^2$ un ángulo $\theta$ en sentido antihorario tiene la matriz:

$$
R_\theta = \begin{bmatrix} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{bmatrix}
$$

In [25]:
# Rotación de 90 grados (π/2 radianes)
theta = np.pi / 2

R = np.array([[np.cos(theta), -np.sin(theta)],
              [np.sin(theta),  np.cos(theta)]])

# Redondear para evitar errores numéricos pequeños
R = np.round(R)

print("Matriz de rotación 90°:")
print(R)
print()

# El vector (1, 0) debería rotar a (0, 1)
e1 = np.array([[1], [0]])
print("e1 = ", e1.flatten())
print("R * e1 =", (R @ e1).flatten(), "← debería ser [0, 1]")
print()

# El vector (0, 1) debería rotar a (-1, 0)
e2 = np.array([[0], [1]])
print("e2 = ", e2.flatten())
print("R * e2 =", (R @ e2).flatten(), "← debería ser [-1, 0]")

Matriz de rotación 90°:
[[ 0. -1.]
 [ 1.  0.]]

e1 =  [1 0]
R * e1 = [0. 1.] ← debería ser [0, 1]

e2 =  [0 1]
R * e2 = [-1.  0.] ← debería ser [-1, 0]


### Ejemplo 3: Reflexión y escalamiento

Otras transformaciones geométricas comunes son la **reflexión** sobre un eje y el **escalamiento**:

In [26]:
# Reflexión sobre el eje x: (x, y) → (x, -y)
R_x = np.array([[1,  0],
                [0, -1]])

# Reflexión sobre el eje y: (x, y) → (-x, y)
R_y = np.array([[-1, 0],
                [ 0, 1]])

# Escalamiento por factor 2 en ambas direcciones
S = np.array([[2, 0],
              [0, 2]])

v = np.array([[3], [4]])

print("Vector original v =", v.flatten())
print()
print("Reflexión sobre eje x:", (R_x @ v).flatten())
print("Reflexión sobre eje y:", (R_y @ v).flatten())
print("Escalamiento x2:      ", (S @ v).flatten())

Vector original v = [3 4]

Reflexión sobre eje x: [ 3 -4]
Reflexión sobre eje y: [-3  4]
Escalamiento x2:       [6 8]


### Composición de transformaciones

Aplicar una transformación $T$ seguida de una transformación $S$ equivale a multiplicar las matrices: $S(T(\mathbf{x})) = (S \cdot T)\mathbf{x}$.

In [27]:
# Rotación 90° y luego reflexión sobre el eje x
theta = np.pi / 2
Rot = np.round(np.array([[np.cos(theta), -np.sin(theta)],
                          [np.sin(theta),  np.cos(theta)]]))
Ref = np.array([[1, 0], [0, -1]])

# Composición: primero rotar, luego reflejar
compuesta = Ref @ Rot

v = np.array([[1], [0]])

print("Rotación 90° de v:", (Rot @ v).flatten())
print("Reflexión del resultado:", (Ref @ (Rot @ v)).flatten())
print()
print("Transformación compuesta (Ref @ Rot):\n", compuesta)
print("Aplicando transformación compuesta:", (compuesta @ v).flatten())

Rotación 90° de v: [0. 1.]
Reflexión del resultado: [ 0. -1.]

Transformación compuesta (Ref @ Rot):
 [[ 0. -1.]
 [-1.  0.]]
Aplicando transformación compuesta: [ 0. -1.]


---
## 7. La Inversa de una Matriz

La **inversa** de una matriz cuadrada $A$ es la matriz $A^{-1}$ tal que:

$$
A \cdot A^{-1} = A^{-1} \cdot A = I
$$

donde $I$ es la matriz identidad.

**No toda matriz cuadrada tiene inversa.** Una matriz $A$ es **invertible** (o no singular) si y solo si su determinante es distinto de cero: $\det(A) \neq 0$.

Cuando existe, la inversa permite resolver sistemas de ecuaciones lineales $A\mathbf{x} = \mathbf{b}$:

$$
A\mathbf{x} = \mathbf{b} \qquad \Rightarrow \qquad \mathbf{x} = A^{-1}\mathbf{b}
$$

### Cálculo del determinante

In [28]:
import numpy.linalg as la

# Matriz invertible
A = np.array([[2., 1.],
              [5., 3.]])

# Matriz no invertible (filas linealmente dependientes)
B = np.array([[1., 2.],
              [2., 4.]])

det_A = la.det(A)
det_B = la.det(B)

print("Matriz A:")
print(A)
print(f"det(A) = {det_A:.2f}  → {'Invertible' if abs(det_A) > 1e-10 else 'NO invertible'}")
print()
print("Matriz B:")
print(B)
print(f"det(B) = {det_B:.2f}  → {'Invertible' if abs(det_B) > 1e-10 else 'NO invertible'}")

Matriz A:
[[2. 1.]
 [5. 3.]]
det(A) = 1.00  → Invertible

Matriz B:
[[1. 2.]
 [2. 4.]]
det(B) = 0.00  → NO invertible


### Cálculo de la inversa

NumPy proporciona la función `numpy.linalg.inv()` para calcular la inversa de una matriz.

In [29]:
A = np.array([[2., 1.],
              [5., 3.]])

A_inv = la.inv(A)

print("Matriz A:")
print(A)
print()
print("Inversa A⁻¹:")
print(A_inv)
print()
print("Verificación A @ A⁻¹ = I:")
print(np.round(A @ A_inv, 10))  # Redondeamos para evitar errores numéricos
print()
print("Verificación A⁻¹ @ A = I:")
print(np.round(A_inv @ A, 10))

Matriz A:
[[2. 1.]
 [5. 3.]]

Inversa A⁻¹:
[[ 3. -1.]
 [-5.  2.]]

Verificación A @ A⁻¹ = I:
[[1. 0.]
 [0. 1.]]

Verificación A⁻¹ @ A = I:
[[1. 0.]
 [0. 1.]]


### Uso de la inversa para resolver sistemas lineales

Dado el sistema $A\mathbf{x} = \mathbf{b}$, podemos encontrar $\mathbf{x} = A^{-1}\mathbf{b}$.

In [30]:
# Sistema de ecuaciones:
# 2x + y  = 5
# 5x + 3y = 13

A = np.array([[2., 1.],
              [5., 3.]])

b = np.array([[5.],
              [13.]])

# Solución usando la inversa
A_inv = la.inv(A)
x = A_inv @ b

print("Sistema A*x = b:")
print("A =", A)
print("b =", b.flatten())
print()
print("Solución x = A⁻¹ * b:")
print(x)
print()
print("Verificación A*x =", (A @ x).flatten(), "(debería ser", b.flatten(), ")")

Sistema A*x = b:
A = [[2. 1.]
 [5. 3.]]
b = [ 5. 13.]

Solución x = A⁻¹ * b:
[[2.]
 [1.]]

Verificación A*x = [ 5. 13.] (debería ser [ 5. 13.] )


In [31]:
# Forma más eficiente: usar numpy.linalg.solve (sin calcular la inversa explícitamente)
x_solve = la.solve(A, b)
print("Solución con la.solve(A, b):")
print(x_solve)
print()
print("Ambos métodos dan el mismo resultado:", np.allclose(x, x_solve))

Solución con la.solve(A, b):
[[2.]
 [1.]]

Ambos métodos dan el mismo resultado: True


### Ejemplo con una matriz 3×3

In [ ]:
# Matriz 3x3
M = np.array([[ 1.,  2., -1.],
              [ 2.,  1.,  3.],
              [-1.,  3.,  2.]])

det_M = la.det(M)
print(f"det(M) = {det_M:.4f}")
print()

if abs(det_M) > 1e-10:
    M_inv = la.inv(M)
    print("Inversa de M:")
    print(np.round(M_inv, 4))
    print()
    print("Verificación M @ M⁻¹:")
    print(np.round(M @ M_inv, 10))
else:
    print("La matriz no tiene inversa.")

In [ ]:
# Intento de invertir una matriz singular
S = np.array([[1., 2., 3.],
              [4., 5., 6.],
              [7., 8., 9.]])

print("Matriz S (singular):")
print(S)
print(f"det(S) = {la.det(S):.6f}")
print()

try:
    S_inv = la.inv(S)
    print("Inversa:", S_inv)
except la.LinAlgError as e:
    print("Error:", e)

### Propiedades de la inversa

Algunas propiedades importantes de la inversa:

$$
(A^{-1})^{-1} = A \qquad (AB)^{-1} = B^{-1}A^{-1} \qquad (A^T)^{-1} = (A^{-1})^T
$$

In [ ]:
A = np.array([[2., 1.], [5., 3.]])
B = np.array([[1., 2.], [3., 7.]])

A_inv = la.inv(A)
B_inv = la.inv(B)

# Propiedad: (A⁻¹)⁻¹ = A
print("(A⁻¹)⁻¹ = A ?")
print("A =", A.flatten())
print("(A⁻¹)⁻¹ =", np.round(la.inv(A_inv), 10).flatten())
print("¿Iguales?", np.allclose(A, la.inv(A_inv)))
print()

# Propiedad: (AB)⁻¹ = B⁻¹ A⁻¹
izq = la.inv(A @ B)
der = B_inv @ A_inv
print("(AB)⁻¹ = B⁻¹ A⁻¹ ?")
print("¿Iguales?", np.allclose(izq, der))

---
## Resumen

| Concepto | Python/NumPy |
|---|---|
| Crear una matriz | `np.array([[...], [...]])` |
| Dimensiones | `A.shape` |
| Acceder elemento $(i,j)$ | `A[i, j]` |
| Transpuesta | `A.transpose()` |
| Suma de matrices | `A + B` |
| Multiplicación por escalar | `k * A` |
| Multiplicación matricial | `A @ B` |
| Matriz identidad | `np.eye(n)` |
| Determinante | `np.linalg.det(A)` |
| Inversa | `np.linalg.inv(A)` |
| Resolver $Ax = b$ | `np.linalg.solve(A, b)` |

---
## Ejercicios

**Ejercicio 1:** Define las matrices $A = \begin{bmatrix}2 & -1 \\ 0 & 3\end{bmatrix}$ y $B = \begin{bmatrix}1 & 4 \\ -2 & 1\end{bmatrix}$. Calcula $2A + 3B$, $AB$, $BA$. ¿$AB = BA$?

In [ ]:
# Escribe tu solución aquí


**Ejercicio 2:** Dada la transformación $T: \mathbb{R}^3 \to \mathbb{R}^2$ definida por:

$$
T\!\left(\begin{bmatrix}x_1\\x_2\\x_3\end{bmatrix}\right) = \begin{bmatrix} x_1 + 2x_2 - x_3 \\ 3x_1 - x_3 \end{bmatrix}
$$

Encuentra la matriz estándar $[T]$ y calcula $T\!\left(\begin{bmatrix}1\\-2\\3\end{bmatrix}\right)$.

In [ ]:
# Escribe tu solución aquí


**Ejercicio 3:** Para la matriz $M = \begin{bmatrix}3 & 1\\2 & 4\end{bmatrix}$:
- Calcula su determinante.
- Encuentra su inversa $M^{-1}$.
- Verifica que $M \cdot M^{-1} = I$.
- Usa la inversa para resolver el sistema $M\mathbf{x} = \begin{bmatrix}7\\10\end{bmatrix}$.

In [ ]:
# Escribe tu solución aquí


**Ejercicio 4:** Genera una matriz cuadrada $A$ de tamaño $4 \times 4$ con enteros aleatorios entre -5 y 5. 
- Verifica si la matriz es invertible comprobando su determinante.
- Si es invertible, calcula $A^{-1}$ y verifica que $AA^{-1} = I$.
- Ejecuta el código varias veces. ¿Siempre es invertible?

In [ ]:
# Escribe tu solución aquí
